# Generated by Django 4.2.5 on 2023-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methane', models.FloatField()),
                ('carbondioxide', models.FloatField()),
                ('ammonia', models.FloatField()),
            ],
        ),
    ]
