# Generated by Django 4.2.5 on 2023-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
