# Generated by Django 4.2.5 on 2023-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_gases_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
