# Generated by Django 4.2.5 on 2023-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_gases_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gases',
            name='float_level',
            field=models.FloatField(default=0),
        ),
    ]
