# Generated by Django 4.2.5 on 2023-10-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_gases_float_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gases',
            old_name='ammonia',
            new_name='hydrogensulfide',
        ),
        migrations.RemoveField(
            model_name='gases',
            name='carbondioxide',
        ),
        migrations.RemoveField(
            model_name='gases',
            name='methane',
        ),
        migrations.AlterField(
            model_name='gases',
            name='float_level',
            field=models.FloatField(),
        ),
    ]
